// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_nnZHsue3i8h1fij6B6PQ1pKTdVjk14c',
    appId: '1:267342947195:web:49ba962299fbfd11c8d3de',
    messagingSenderId: '267342947195',
    projectId: 'flutter-projects-fab94',
    authDomain: 'flutter-projects-fab94.firebaseapp.com',
    storageBucket: 'flutter-projects-fab94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC11KoQCEReZqvcn7nJWkLCBY-qyQtvEk',
    appId: '1:267342947195:android:ed84cd69813e09c4c8d3de',
    messagingSenderId: '267342947195',
    projectId: 'flutter-projects-fab94',
    storageBucket: 'flutter-projects-fab94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBByZxHc_MGMTon_ZKyTZ_QMsZ0gnvBfSE',
    appId: '1:267342947195:ios:9d0c1ab4bd4bd367c8d3de',
    messagingSenderId: '267342947195',
    projectId: 'flutter-projects-fab94',
    storageBucket: 'flutter-projects-fab94.appspot.com',
    iosClientId: '267342947195-t04d8ehmt42c6226e6qll0npald9jgf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBByZxHc_MGMTon_ZKyTZ_QMsZ0gnvBfSE',
    appId: '1:267342947195:ios:65cb9d2b2239f758c8d3de',
    messagingSenderId: '267342947195',
    projectId: 'flutter-projects-fab94',
    storageBucket: 'flutter-projects-fab94.appspot.com',
    iosClientId: '267342947195-hfvd21uatsq06kq651jhollivgl0coa3.apps.googleusercontent.com',
    iosBundleId: 'com.example.widgetsApp.RunnerTests',
  );
}
